export const Crops = [
    {name:'Beans'},
    {name:'Rice'},
    {name:'Sesame (BeniSeed)'},
    {name:'Cashew'},
    {name:'Cassava'},
    {name:'Cocoa'},
    {name:'Groundnut'},
    {name:'Gum Arabic'},
    {name:'Kolanut'},
    {name:'Maize'},
    {name:'Melon'},
    {name:'Millet'},
    {name:'Palm Kernel'},
    {name:'Plantain'},
    {name:'Rubber'},
    {name:'Sorghum (Guinea Corn)'},
    {name:'Soybeans'},
    {name:'CowPea'},
    {name:'Yam'},
    {name:'Potato'},
    {name:'Tobacco'},
    {name:'Mango'},
    {name:'Pineapple'},
    {name:'Orange'},
    {name:'Guava'},
    {name:'Paw Paw'},
    {name:'Onion'},
    {name:'Tomato'},
    {name:'Sugar Cane'},
    {name:'Cotton'},
    {name:'Carrot'},
    {name:'Timber'},
    {name:'Okra'},
    {name:'Pepper'},
    {name:'Amaranthus'},
    {name:'Ewedu'},
    {name:'Sobo'},
    {name:'Baobab Leaves'},
    {name:'Banana'},
    {name:'Vegetable Leafs'}
  ]
